#!/usr/bin/env node
// Turn the maps/ folders into the one list the app can read.
//
// Each state's truth is `maps/<state>/region.json`, next to that state's data
// and the notes describing how it was built. Nothing outside maps/ names a
// state -- but a browser cannot list a directory, so the folders are collected
// here into `maps/states.js`, a classic script index.html and sw.js load
// before region.js.
//
// It is a build artefact, checked in like build-version.js: adding a state is
// adding a folder and running `npm run maps:registry`.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MAPS = join(ROOT, 'maps');

// The one home of "which file carries each dataset". sw.js precaches these
// paths, build_mobile_shell.mjs bundles them, and the map-store installer
// downloads them -- all three read the file lists this script bakes into
// maps/index.json rather than keeping their own copy of this table.
const DATASET_FILES = {
  bikeroutes: 'bikeroutes.geojson.gz',
  restrictions: 'bike_restrictions.geojson.gz',
  closures: 'route_closures.geojson.gz',
  roads: 'roads.pmtiles',
  basemap: 'basemap.pmtiles',
  overlays: 'overlays.pmtiles',
  graph: 'graph2.bin.gz',
  places: 'places.json',
};

// Every key a state may declare. An unknown key is a typo -- silently ignoring
// it is how a state ends up shipping with, say, `defaultZoomLevel` and opening
// at the wrong scale with nothing to show for it.
const KNOWN = new Set(['id', 'name', 'status', 'readiness', 'summary', 'bounds',
  'defaultCenter', 'defaultZoom', 'stressAgency', 'restrictionAgency', 'speedAgency',
  'facilitySourceName', 'stressLayerName', 'restrictionLayerName',
  'interstateRoutePrefixes', 'facilityLevels', 'sourceCounts', 'routeDirectionSuffixes',
  'datasets', 'versions', 'attribution']);
const REQUIRED = ['id', 'name', 'status', 'bounds', 'defaultCenter', 'defaultZoom', 'datasets'];

const states = [];
for (const entry of readdirSync(MAPS, { withFileTypes: true }).sort((a, b) =>
  a.name.localeCompare(b.name))) {
  if (!entry.isDirectory()) continue;
  const configPath = join(MAPS, entry.name, 'region.json');
  let config;
  try {
    config = JSON.parse(readFileSync(configPath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') throw new Error(`maps/${entry.name}/ has no region.json`);
    throw new Error(`maps/${entry.name}/region.json is not valid JSON: ${error.message}`);
  }
  for (const key of REQUIRED) {
    if (config[key] === undefined) throw new Error(`maps/${entry.name}/region.json omits "${key}"`);
  }
  for (const key of Object.keys(config)) {
    if (!KNOWN.has(key)) throw new Error(`maps/${entry.name}/region.json has unknown key "${key}"`);
  }
  if (config.id !== entry.name) {
    throw new Error(`maps/${entry.name}/region.json declares id "${config.id}"`);
  }
  // A declared dataset whose file is missing would ship a state that 404s on
  // first use; measuring the files here both catches that and gives the store
  // index the sizes a download UI needs.
  const files = [];
  for (const [dataset, file] of Object.entries(DATASET_FILES)) {
    if (!config.datasets[dataset]) continue;
    const filePath = join(MAPS, entry.name, file);
    let stat;
    try {
      stat = statSync(filePath);
    } catch (e) {
      throw new Error(`maps/${entry.name}/region.json declares "${dataset}" but ${file} is missing`);
    }
    files.push({ dataset, path: file, bytes: stat.size });
  }
  states.push({ config, files });
}
if (!states.length) throw new Error('maps/ holds no states');

const body = states.map(({ config }) => `  ${JSON.stringify(config)},`).join('\n');
writeFileSync(join(MAPS, 'states.js'), `/* GENERATED by scripts/build_map_registry.mjs -- do not edit.
 *
 * One entry per maps/<state>/region.json, in folder order. A browser cannot
 * list a directory, so the folders are indexed here; region.js picks which one
 * this session is running on. Rebuild with \`npm run maps:registry\`.
 *
 * Loaded as a classic script by index.html and via importScripts() by sw.js,
 * so it must not use module syntax. In Node the IIFE's \`this\` is
 * module.exports, so tests and build scripts can require() it.
 */
(function (root) {
  // False in a slim native shell: the states are known but their data files
  // are not on this origin, so using one means downloading it from a store.
  root.MAP_STATES_BUNDLED = true;
  root.MAP_STATES = [
${body}
  ];
}(typeof self !== 'undefined' ? self : this));
`);

// The same registry as pure data, plus per-file sizes: the map-store contract.
// A store is any HTTPS directory serving this file beside the state folders it
// describes; the app's installer reads it, and so does build_mobile_shell.mjs.
writeFileSync(join(MAPS, 'index.json'), `${JSON.stringify({
  storeFormat: 1,
  states: states.map(({ config, files }) => ({ ...config, files })),
}, null, 1)}\n`);

console.log(`indexed ${states.length} state${states.length === 1 ? '' : 's'} -> maps/states.js, maps/index.json`);
for (const { config, files } of states) {
  const bytes = files.reduce((sum, file) => sum + file.bytes, 0);
  console.log(`  ${config.id.padEnd(12)} ${config.status.padEnd(9)} ${(bytes / 1048576).toFixed(0)} MB in ${files.length} files`);
}
